name: BlogBackEndDeploy

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'server/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./server
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get NPM Cache Directory Path
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Get Yarn Cache Directory Path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-     

    - name: Install Nest Cli 
      run: npm install @nestjs/cli -g

    - name: Install Dependencies
      run: yarn

    - name: Build Server
      run: yarn build

    - name: Get Package Version
      id: get-package-version
      uses: martinbeentjes/npm-get-version-action@master
      with: 
        path: ./server
   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
   
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: juzisang/blog-back-end:latest,juzisang/blog-back-end:${{ steps.get-package-version.outputs.current-version }}
        cache-from: type=registry,ref=juzisang/blog-back-end:latest
        cache-to: type=inline

    - if: ${{ github.ref == 'refs/heads/master' }}
      name: Deploy Prod Server
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER_NAME }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: sudo docker stack deploy -c ./sites-manage/nodejs-blog-compose.yml nodejs-blog

    - if: ${{ github.ref == 'refs/heads/dev' }}
      name: Deploy Test Server
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER_NAME }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: sudo docker stack deploy -c ./sites-manage/nodejs-test-blog-compose.yml nodejs-test-blog